# Generated by Django 3.1.4 on 2021-01-11 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210104_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countgoodandbad',
            name='movie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='countgoodandbads', to='core.movie'),
        ),
    ]
