# Generated by Django 3.1.4 on 2021-01-12 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210111_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieimage',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='movieimages',
            field=models.ManyToManyField(blank=True, to='core.MovieImage'),
        ),
        migrations.AddField(
            model_name='movieimage',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movieimage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='images',
            field=models.ImageField(blank=True, upload_to='./django_media/', verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='movieimage',
            name='images',
            field=models.ImageField(blank=True, upload_to='./django_media/'),
        ),
    ]
