# Generated by Django 3.1.4 on 2021-01-12 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210112_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieimage',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='movieimages',
            field=models.ManyToManyField(blank=True, to='core.MovieImage'),
        ),
        migrations.AddField(
            model_name='movieimage',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movieimage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.user'),
            preserve_default=False,
        ),
    ]
