# Generated by Django 3.1.4 on 2021-01-12 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210112_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movieimages',
        ),
        migrations.RemoveField(
            model_name='movieimage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='movieimage',
            name='user',
        ),
        migrations.AddField(
            model_name='movieimage',
            name='movie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='movieimages', to='core.movie'),
        ),
    ]
