# Generated by Django 3.1.4 on 2021-01-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210112_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieimage',
            name='images',
            field=models.ImageField(blank=True, upload_to='./django_media/', verbose_name='Image_path'),
        ),
    ]
