# Generated by Django 3.1.4 on 2021-01-12 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210112_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderMovieImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='./django_media/', verbose_name='Image_path')),
                ('movie', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='slidermovieimages', to='core.movie')),
            ],
        ),
        migrations.DeleteModel(
            name='MovieImage',
        ),
    ]
