# Generated by Django 3.1.4 on 2021-01-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210112_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidermovieimage',
            name='images',
            field=models.ImageField(blank=True, upload_to='./upload_images/', verbose_name='Image_path'),
        ),
    ]
