# Generated by Django 3.1.4 on 2021-01-13 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210112_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last_modified'),
        ),
    ]
